import { useMemo, useState } from "react";
import { AreaChart, BarChart3, CircleDollarSign, PiggyBank, TrendingDown, Zap } from "lucide-react";
import { Area, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { estimateCost, MODEL_PRICING } from "@/lib/tokenopt-api";
import type { ModelId } from "@/lib/tokenopt-types";
import { PageIntro } from "./app-shell";
import { MetricCard, SectionHeading } from "./shared";

const pareto = [{ name: "No optimization", tokens: 18420, quality: 95.2 }, { name: "Deduplication", tokens: 15600, quality: 95.3 }, { name: "Context pruning", tokens: 11400, quality: 95.1 }, { name: "History summary", tokens: 8100, quality: 94.9 }, { name: "Tool trimming", tokens: 6500, quality: 95.1 }, { name: "Full optimization", tokens: 5420, quality: 95.5 }];
const fmtMoney = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
const compact = (n: number) => new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 1 }).format(n);

export function AnalyticsDashboard() {
  const [requests, setRequests] = useState(1_000_000); const [inputTokens, setInputTokens] = useState(25_000); const [outputTokens, setOutputTokens] = useState(1_000); const [model, setModel] = useState<ModelId>("bedrock");
  const estimate = useMemo(() => estimateCost({ requests, inputTokens, outputTokens, model }), [requests, inputTokens, outputTokens, model]);
  const requestData = [0.25, 0.5, 0.75, 1].map((ratio) => ({ requests: `${ratio}M`, before: estimate.beforeCost * ratio, after: estimate.afterCost * ratio }));
  const tokenData = [{ name: "Without TokenOpt", tokens: estimate.beforeTokens / 1e9 }, { name: "With TokenOpt", tokens: estimate.afterTokens / 1e9 }];
  return <main className="page-container py-10 sm:py-14"><PageIntro eyebrow="Analytics" title="Cost Simulator" description="Model your token volume, compare operating costs, and explore the quality-efficiency frontier." />
    <section className="mt-7 grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><div className="rounded-lg border border-border bg-card p-5"><h2 className="font-semibold">Workload assumptions</h2><div className="mt-5 space-y-4"><Field label="Monthly Requests"><Input type="number" min="0" value={requests} onChange={(e) => setRequests(Number(e.target.value) || 0)} /></Field><Field label="Average Input Tokens"><Input type="number" min="0" value={inputTokens} onChange={(e) => setInputTokens(Number(e.target.value) || 0)} /></Field><Field label="Average Output Tokens"><Input type="number" min="0" value={outputTokens} onChange={(e) => setOutputTokens(Number(e.target.value) || 0)} /></Field><Field label="Model"><Select value={model} onValueChange={(v) => setModel(v as ModelId)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(MODEL_PRICING).map(([id, p]) => <SelectItem key={id} value={id}>{p.label}</SelectItem>)}</SelectContent></Select></Field></div><p className="mt-5 border-t border-border pt-4 text-xs leading-5 text-muted-foreground">Pricing is configurable by model and kept outside the interface calculations.</p></div>
      <div className="grid gap-3 sm:grid-cols-2"><MetricCard label="Without TokenOpt" value={`${compact(estimate.beforeTokens)} tokens`} detail={`${fmtMoney(estimate.beforeCost)} / month`} icon={BarChart3} /><MetricCard label="With TokenOpt" value={`${compact(estimate.afterTokens)} tokens`} detail={`${fmtMoney(estimate.afterCost)} / month`} icon={Zap} tone="success" /><div className="metric-card metric-card-featured sm:col-span-2"><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase text-muted-foreground">Estimated Savings</span><PiggyBank className="size-5 text-primary" /></div><div className="mt-4 font-mono text-4xl font-semibold text-primary">{fmtMoney(estimate.monthlySavings)} <span className="text-base text-muted-foreground">/ month</span></div><p className="mt-2 text-sm text-muted-foreground">{fmtMoney(estimate.monthlySavings * 12)} / year</p></div></div>
    </section>
    <section className="mt-12"><SectionHeading title="Cost & Volume" description="Projected savings scale with request volume." /><div className="grid gap-4 lg:grid-cols-2"><ChartCard title="Requests vs Cost"><ResponsiveContainer width="100%" height="100%"><LineChart data={requestData}><CartesianGrid stroke="var(--border)" /><XAxis dataKey="requests" tick={{ fontSize: 11 }} /><YAxis tickFormatter={compact} tick={{ fontSize: 11 }} /><Tooltip formatter={(v: number) => fmtMoney(v)} contentStyle={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: 6 }} /><Line type="monotone" dataKey="before" stroke="var(--chart-before)" strokeWidth={2} /><Line type="monotone" dataKey="after" stroke="var(--chart-after)" strokeWidth={2} /></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Tokens Before vs After"><ResponsiveContainer width="100%" height="100%"><BarChart data={tokenData}><CartesianGrid stroke="var(--border)" vertical={false} /><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} unit="B" /><Tooltip contentStyle={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: 6 }} /><Bar dataKey="tokens" fill="var(--chart-after)" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer></ChartCard></div></section>
    <section className="mt-12"><SectionHeading title="Quality vs Token Usage" description="Each optimization level reduces context while quality remains above threshold." /><ChartCard title="Pareto curve"><ResponsiveContainer width="100%" height="100%"><LineChart data={[...pareto].reverse()} margin={{ left: 10, right: 20 }}><CartesianGrid stroke="var(--border)" /><XAxis dataKey="tokens" type="number" domain={[4000, 20000]} tick={{ fontSize: 11 }} /><YAxis domain={[90, 100]} tick={{ fontSize: 11 }} unit="%" /><Tooltip contentStyle={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: 6 }} /><Line type="monotone" dataKey="quality" stroke="var(--primary)" strokeWidth={3} dot={{ fill: "var(--primary)", r: 5 }} /></LineChart></ResponsiveContainer></ChartCard></section>
  </main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-muted-foreground">{label}</span>{children}</label>; }
function ChartCard({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-lg border border-border bg-card p-4"><h3 className="mb-3 text-sm font-semibold">{title}</h3><div className="h-72">{children}</div></div>; }
