import { useState } from "react";
import { Check, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { PageIntro } from "./app-shell";

export function SettingsDashboard() { const [saved, setSaved] = useState(false); return <main className="page-container py-10 sm:py-14"><PageIntro eyebrow="Preferences" title="Settings" description="Set quality safeguards and default context sources for new optimization runs." /><div className="mt-8 max-w-3xl space-y-4"><section className="rounded-lg border border-border bg-card p-5 sm:p-6"><h2 className="font-semibold">Optimization defaults</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label><span className="mb-1.5 block text-xs font-semibold text-muted-foreground">Quality threshold</span><div className="relative"><Input type="number" defaultValue="90" min="0" max="100" className="pr-8" /><span className="absolute right-3 top-2 text-sm text-muted-foreground">%</span></div></label><label><span className="mb-1.5 block text-xs font-semibold text-muted-foreground">Default model</span><Select defaultValue="bedrock"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="bedrock">Amazon Bedrock</SelectItem><SelectItem value="gpt">GPT</SelectItem><SelectItem value="claude">Claude</SelectItem><SelectItem value="custom">Custom Model</SelectItem></SelectContent></Select></label></div></section><section className="rounded-lg border border-border bg-card p-5 sm:p-6"><h2 className="font-semibold">Default context</h2><div className="mt-4 divide-y divide-border">{["Conversation History", "Documents", "Tool Definitions"].map((label) => <div key={label} className="flex items-center justify-between py-4"><span className="text-sm">{label}</span><Switch defaultChecked aria-label={`Default ${label}`} /></div>)}</div></section><Button onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 1800); }}><Check />{saved ? "Settings saved" : "Save Settings"}</Button></div></main>; }
